apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    domain: hello-world
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    domain: hello-world
  type: ClusterIP
